---
service:
  name: "full-stack-developer-workspace"
provider:
  name: "aws"
  environment: "${file(../.env/${self:provider.stage}.yml):provider.environment, file(.env/${self:provider.stage}.yml):provider.environment}"
  profile: "kalarrs"
  region: "us-west-2"
  stage: "${opt:stage, \"dev\"}"
resources:  # CloudFormation template syntax
  Resources:
    ToppingsBucket:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
            - Id: CleanupTemp
              Prefix: temp
              Status: Enabled
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 1
              ExpirationInDays: 1
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
              MaxAge: 3000
  Outputs:
    ToppingsBucketName:
      Value:
        Ref: ToppingsBucket
      Export:
        Name: ToppingsBucket
custom:
  layers: "${file(../.env/${self:provider.stage}.yml):custom.layers, file(.env/${self:provider.stage}.yml):custom.layers}"
