---
provider:
  environment:
    MONGO_URI: ${ssm:DEV_MONGO_URI~true}
    TOPPING_COLLECTION: "toppings"
    PIZZA_COLLECTION: "pizzas"
custom:
  layers:
    node-modules: arn:aws:lambda:us-west-2:948834093743:layer:full-stack-developer-node-modules-layer-dev:1
