---
provider:
  environment:
    MONGO_URI: ${ssm:DEV_MONGO_URI~true}
    TOPPING_COLLECTION: "toppings"
    PIZZA_COLLECTION: "pizzas"
custom:
  layers:
    node-modules: ${ssm:dev_node-modules-layer-arn}
