---
service: toppings

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-project-utils"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  timeout: 30
  memorySize: 128
  environment:
    MONGO_URI: ${file(../serverless.yml):provider.environment.MONGO_URI}
    TOPPING_COLLECTION: ${file(../serverless.yml):provider.environment.TOPPING_COLLECTION}
    TOPPINGS_S3_BUCKET: ${cf:full-stack-developer-workspace-${file(../serverless.yml):provider.stage}.ToppingsBucketName}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.TOPPINGS_S3_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.TOPPINGS_S3_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "rekognition:GetLabelDetection"
        - "rekognition:DetectLabels"
        - "rekognition:DetectText"
      Resource: "*"

functions:
  createToppingImageSingedUrl:
    handler: src/handler.createToppingImageSingedUrl
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: POST
          path: topping-image-signed-url
          cors: true
  createTopping:
    handler: src/handler.createTopping
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: POST
          path: toppings
          cors: true
  getToppings:
    handler: src/handler.getToppings
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: GET
          path: toppings
          cors: true
  deleteTopping:
    handler: src/handler.deleteTopping
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: DELETE
          path: toppings/{toppingId}
          cors: true

  updateTopping:
    handler: src/handler.updateTopping
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: PUT
          path: toppings/{toppingId}
          cors: true

  detectTopping:
    handler: src/handler.detectTopping
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: POST
          path: detect-topping
          cors: true

custom:
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  layers:
    node-modules: ${file(../serverless.yml):custom.layers.node-modules}
