---
service: pizzas

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-project-utils"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  memorySize: 128
  environment:
    MONGO_URI: ${file(../serverless.yml):provider.environment.MONGO_URI}
    PIZZA_COLLECTION: ${file(../serverless.yml):provider.environment.PIZZA_COLLECTION}
    TOPPINGS_S3_BUCKET: ${cf:full-stack-developer-workspace-${file(../serverless.yml):provider.stage}.ToppingsBucketName}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.TOPPINGS_S3_BUCKET}/*"

functions:
  createPizza:
    handler: src/handler.createPizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: POST pizzas
  getPizzas:
    handler: src/handler.getPizzas
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: GET pizzas
  deletePizza:
    handler: src/handler.deletePizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: DELETE pizzas/{pizzaId}
  updatePizza:
    handler: src/handler.updatePizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: PUT toppings/{toppingId}

custom:
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  layers:
    node-modules: ${file(../serverless.yml):custom.layers.node-modules}
