---
provider:
  environment:
    MONGO_URI: "mongodb+srv://demo:demo@cluster0-rxatp.mongodb.net/pizza?authMechanism=SCRAM-SHA-1&authSource=pizza&retryWrites=true&ssl=true"
    TOPPING_COLLECTION: "toppings"
