---
service: toppings

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-project-utils"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  memorySize: 128
  environment:
    MONGO_URI: ${file(../serverless.yml):provider.environment.MONGO_URI}
    TOPPING_COLLECTION: ${file(../serverless.yml):provider.environment.TOPPING_COLLECTION}
    TOPPINGS_S3_BUCKET: ${cf:full-stack-developer-workspace-${file(../serverless.yml):provider.stage}.ToppingsBucketName}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.TOPPINGS_S3_BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.TOPPINGS_S3_BUCKET}/*"

functions:
  createTopping:
    handler: src/handler.createTopping
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: POST toppings
  getToppings:
    handler: src/handler.getToppings
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http: GET toppings

resources:  # CloudFormation template syntax
  Resources:
    ToppingsBucket:
      Type: AWS::S3::Bucket

  Outputs:
    AttachmentsBucketName:
      Value:
        Ref: AttachmentsBucket
      Export:
        Name: ${self:service}:${file(../serverless.yml):provider.stage}:AttachmentsBucket

custom:
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  layers:
    node-modules: ${file(../serverless.yml):custom.layers.node-modules}
