---
service: pizzas

plugins:
  - serverless-webpack
  - "@kalarrs/serverless-project-utils"

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  timeout: 30
  memorySize: 128
  environment:
    MONGO_URI: ${file(../serverless.yml):provider.environment.MONGO_URI}
    PIZZA_COLLECTION: ${file(../serverless.yml):provider.environment.PIZZA_COLLECTION}
    PIZZAS_S3_BUCKET: ${cf:full-stack-developer-workspace-${file(../serverless.yml):provider.stage}.PizzasBucketName}
    PIZZA_TEMP_IMAGE_PREFIX: "temp"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.PIZZAS_S3_BUCKET}/*"

functions:
  createPizzaImageSingedUrl:
    handler: src/handler.createPizzaImageSingedUrl
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: POST
          path: pizza-image-signed-url
          cors: true
  createPizza:
    handler: src/handler.createPizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: POST
          path: pizzas
          cors: true
  getPizzas:
    handler: src/handler.getPizzas
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: GET
          path: pizzas
          cors: true
  deletePizza:
    handler: src/handler.deletePizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: DELETE
          path: pizzas/{pizzaId}
          cors: true
  updatePizza:
    handler: src/handler.updatePizza
    layers:
      - ${self:custom.layers.node-modules}
    events:
      - http:
          method: PUT
          path: pizzas/{pizzaId}
          cors: true

custom:
  localDevPort: 5000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
  layers:
    node-modules: ${file(../serverless.yml):custom.layers.node-modules}
